### ISSUE TITLE
HiKey: issue starting linux kernel with Android + OP-TEE

### ISSUE THREAD

**Issue by ppeiffer** [96boards/documentation#61] opened 2017-03-17 10:52 UTC
Hi,

I'm fighting by trying to setup and to use Android + optee on HiKey.
I tried two setup:
- Android 6.0 + kernel 4.1 + op-tee
- latest: Android 7.0 + kernel 4.9 + op-tee
I'm using Lemaker version of HiKey, (8GB eMMC, 2G of RAM). I have connected serial line on UART3
All ASOP images and op-tee compiled fine, etc.

When I run them, in both case, I can see TEE started (I have some TEE-CORE log), but then the switch to linux kernel fails.
It ends with the boot sequence from UEFI:

[...]
DEBUG:   [0x0] TEE-CORE:spi_init:168: configure gpio6 pins 0-3 as SPI
DEBUG:   [0x0] TEE-CORE:spi_init:174: configure gpio6 pins 0-3 as nopull
INFO:    TEE-CORE: Initialized
DEBUG:   [0x0] TEE-CORE:init_primary_helper:629: Primary CPU switching to normal world boot
UEFI firmware (version PreAlpha built at 16:45:58 on Feb 28 2017)

Fail to start BootNext.
The default boot selection will start in   1 seconds
[1] fastboot
[2] boot from eMMC
[3] boot from SD card
[4] Shell
[5] Boot Manager

Any ideas about what's wrong, where to look for ?

Thansk

**Comment by vchong** [comment] 2017-03-17 11:00
Hi @ppeiffer,

You'd requested Android 6.0 + kernel 4.1 + op-tee previously at a different channel but this setup has bit-rotted somewhat and hard to reproduce. For Android 7.0 + kernel 4.9 + op-tee, please try https://github.com/linaro-swg/optee_android_manifest/tree/hikey-n-4.9. This was put up yesterday and might still have some kinks, so feedback is welcome.

Thanks!

**Comment by ppeiffer** [comment] 2017-03-20 11:15
Hi @vchong,

Yes, android 6.0 was my first willing, but without success, I switched to android 7.0 to, at least, try to have something that works first (then, I may switch back to android 6.0 & co later on).

Your setup works (!!), thanks !
I'm able to connect on the target through the serial line, xtest reports few errors that your are probably already aware of:
+-----------------------------------------------------
23290 subtests of which 14 failed
70 test cases of which 13 failed
0 test case was skipped
TEE test application done!

Otherwise, here are few comments or feedback:
- A minor fix in the wiki page, section 4 about flash-all.sh script. It is now located under
./device/linaro/hikey/installer/hikey/flash-all.sh
- I can't connect with adb though mini-usb: here are the check I did so far
  . "adb devices" shows nothing and even with lsusb on the host, I don't see any new usb device
  . on target, I noticed these errors in kernel log when I plug the USB:
[  738.324781] binder: 2184:2205 transaction failed 29189, size 96-0
[  740.749011] dwc2 f72c0000.usb: Do port resume before switching to device mode
[  740.826846] dwc2 f72c0000.usb: dwc2_hsotg_enqueue_setup: failed queue (-11)
[  741.274477] dwc2 f72c0000.usb: new device is high-speed
[  746.346279] dwc2 f72c0000.usb: new device is high-speed

All Android specific options seems enable in kernel config (at least, from what I checked so far)

- my HDMI screen doesn't work:  I didn't check anything so far, ie what's enable or what is missing so far

Thanks,

**Comment by vchong** [comment] 2017-03-20 17:58
Hi @ppeiffer you're welcome!

> xtest reports few errors

Just to gather data, did you try running it as root and does it make a difference?

> minor fix in the wiki page

Fixed. Thanks!

The adb and HDMI issues aren't really OP-TEE related so hopefully someone else can chip in here. Best I can offer is if you don't have access to a serial console, perhaps try adb over tcp/wifi? For the screen, please see http://www.96boards.org/documentation/ConsumerEdition/HiKey/HardwareDocs/HardwareNotes.md/ for notes on supported resolutions.

**Comment by vchong** [comment] 2017-03-21 07:00
@ppeiffer 

Some update regarding adb. Please try below and then restart adb to see if it works.
```
setprop sys.usb.configfs 1
setprop persist.adb.tcp.port ""
```

**Comment by ppeiffer** [comment] 2017-03-22 14:34
Hi @vchong ,

> Just to gather data, did you try running it as root and does it make a difference?

Yes, it does. I got following results when run as root:
23512 subtests of which 4 failed
70 test cases of which 2 failed
0 test case was skipped

> Some update regarding adb. Please try below and then restart adb to see if it works.

Indeed, it fixes the adb issue, thanks !

**Comment by vchong** [comment] 2017-03-22 15:22
> 23512 subtests of which 4 failed

Can you please list the test numbers? How old is your build? If the latest commit for `android-patchsets` is not `c50f08026f9c8c2a703efc7f70dfc38f3186a005 - Update 17177 to v6`, are you able to update (repo sync) all your repos, rebuild and run xtest again as non-root and get back with the results? Some new rules were added.

> Indeed, it fixes the adb issue, thanks !

Great, but please note that now you can't do adb over tcp. This is a known issue being looked at.

**Comment by vchong** [comment] 2017-03-23 15:12
@ppeiffer Please NOTE if you run repo sync, you'll have to reapply all the patches again since they would be discarded under default settings, i.e. repo sync, run step 3.4 again, and then build again.

**Comment by ppeiffer** [comment] 2017-03-23 16:13
So yes, I was at commit `c50f08026f9c8c2a703efc7f70dfc38f3186a005 - Update 17177 to v6` but I did `repo sync` anyway.

The failures I got for now are on tests 6003.[12], 6004.[12], 6008.[12], 6009.[12], 60010.[12] + all from 20001 tp 20523

**Comment by vchong** [comment] 2017-03-23 16:26
Please just make sure to reapply the patches every time you repo sync.

Thanks for getting back with the results! So this running xtest NOT as root right? If so, then you can probably go ahead and proceed with what you want to do with the build. We're looking into the failures but will probably take some time. However, please note that the failures don't necessarily mean something is broken with OP-TEE itself. I think all of these are related to SELinux rules and file permissions.

Ok to close this?

**Comment by ppeiffer** [comment] 2017-03-23 16:32
> Please just make sure to reapply the patches every time you repo sync.

Yes, I did, no worry.

> So this running xtest NOT as root right?
Yes, correct (NOT root)

Ok to close this, thanks !

**Comment by vchong** [comment] 2017-03-23 16:40
Thanks and have fun! : )

**Closed by vchong** 2017-03-23 16:40 UTC
