### ISSUE TITLE
Bubblegum 96 kernel update breaks Linaro CI builds

### ISSUE THREAD

**Issue by ProfFan** [96boards/documentation#110] opened 2017-08-02 11:02 UTC
The latest update on the vendor kernel repo broke the Linaro CI build. See https://ci.linaro.org/job/96boards-bubblegum/17/

**Comment by Mani-Sadhasivam** [comment] 2017-10-09 07:53
@fboudra . Can you please look into it?

**Comment by daniel-thompson** [comment] 2017-10-09 08:29
It is possible to do plenty of triage first without help from B&B... jenkins is pretty transparent and we can see most of what we need in the "Console output".

So...

AFAICT the build failure occurs because the vendor kernel has no bindeb-pkg rule. After a little digging with  git blame and git describe we can tell that this is hardly surprising, the vendor kernel is v3.10 based and the bindeb-pkg rule did not arrive until @suihkulokki delivered changes to v4.1 (https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git/commit/?id=3716001bcb7f5822382ac1f2f54226b87312cc6b ).

Thus we can assume this is not caused by any change to the vendor kernel (it has never had a bindeb-pkg). Instead it looks like it is provoked by this change from @ndechesne to the build scripts:
https://git.linaro.org/ci/lci-build-tools.git/commit/?id=b7f8b94203a39304215e546543d8d451fda02458

This leaves us in a slightly difficult position... bindeb-pkg in recent kernels is pretty much equivalent to deb-pkg in older kenrels. Do we need the build-tools to automatically figure out the version... or should we just require the bubblegum kernel to backport the Riko's changes?

**Comment by fboudra** [comment] 2017-10-09 08:42
I recommend to backport the changes from latest code in mainline. It's pretty straight forward.

**Comment by daniel-thompson** [comment] 2018-01-25 14:52
I think we might finally looking at fixing this: https://github.com/96boards-bubblegum/linux/pull/6

Also, whilst this is certainly an issue, it isn't really an issue with the documentation so I'm going to close this one now.

**Closed by daniel-thompson** 2018-01-25 14:52 UTC
Labels: Under Review
