### ISSUE TITLE
No/Only Limited video and audio on the HiKey 

### ISSUE THREAD

**Issue by Graphicscore** [96boards/documentation#46] opened 2016-12-27 08:29 UTC
Hello, I am currently experience alot of trouble with the HiKey board, I'm working in a company and we're currently trying to evaluate the HiKey as one of our main development boards. The Boards look pretty good but we have some really serious problems regarding video and audio playback. The specification sheet says video and and audio decoding is support (at least h.264 and AAC audio) but all I can see is that **video's stutter alot and if a video has audio it's not going to play at all.** We're testing this on AOSP built of the Android OS and are using the build in video player and/or the ExoPlayer demo application. The main-goal we are trying to archive is running a custom built Android OS with full media support. We've successfully compiled several Android versions as of 6.0 , 6.0.1, 7.0 and 7.1 from AOSP source which all show this behavior furthermore being worse the newer we push the version but even the officially provided update package from google (which is still 5.0.1) will not play videos with audio but only without. We're using the fastboot method to update the HiKey. Can someone tell me if we're doing something wrong ? If we compile the OS from AOSP source do we have to include special media drivers or do we need to checkout a completely different repo ? , we followed the documentation closely provided on googles developer website and we we're able to compile alot of roms for other devices too. We would really like to use the device but in the state of right now it's absolutely unusable for us and kind of disappointing regarding the fact that it is googles "reference board", I hope we're just doing it wrong.

Best Regards,

**Comment by sdrobertw** [comment] 2016-12-28 08:08
Hello @Graphicscore 

Glad to hear you have picked up and began working with the HiKey. I will look further into this issue in the coming week.

Out of curiosity, have you tried any of the pre-built images available here?:

http://builds.96boards.org/releases/reference-platform/aosp/hikey/16.03/

**Comment by Graphicscore** [comment] 2016-12-28 21:19
Hi @sdrobertw ,

as of right now I've just played around with own builds or the package provided on the googles website(https://developers.google.com/android/images-preview), I think I've tried some builds of the builds.96boards.org, but to be honest I tried out so many I can't remember. I'm don't have physical access to the device right now because it's already evening here. I'll install one of your provided builds tomorrow morning when I return to the office.

**Comment by Graphicscore** [comment] 2016-12-29 07:25
Wait, rust read the PDF, Audio over HDMI is not supported ?

**Comment by sdrobertw** [comment] 2017-01-03 15:51
@Graphicscore Happy New Year!

Don't worry about testing every build.

Unfortunately I have been told, there is no HW media support at the moment and there is a risk that there will never be any.

I will continue to look into this. my suggestion is to leave the issue open for a bit longer.

I hope this helps.

**Comment by sdrobertw** [comment] 2017-01-03 22:15
@Graphicscore Happy New Year!

Don't worry about testing every build. I have been told HW decode is not currently supported. As a result stuttering may be experienced. This is due to the device reaching thermal limits using software decoding and having to reduce the processor performance accordingly. 

While we are unsure as to when this will be addressed for Android on the HiKey, I would suggest checking out other boards and builds within the 96Boards family!

http://www.96boards.org/products/ce/

DragonBoard 410c and MediaTek X20 both run Android builds and I have been assured the DB410c offers HW decoding.

---

As for audio over HDMI (for the HiKey), this should be working though is does require 4.4 kernel.

Which PDF were you using as reference?

Thank you, I hope this helps.

**Comment by Graphicscore** [comment] 2017-01-04 21:54
@sdrobertw Happy New Year to you aswell !

The Audio over HDMI was described in an PDF that's in the latest build directory.

http://builds.96boards.org/releases/reference-platform/aosp/hikey/16.03/CE-AOSP-RPB-16.03-HiKey-TestReport.pdf

**Comment by idlethread** [comment] 2017-01-05 06:21
@Graphicscore 

HDMI audio is working and you can get preview images for Hikey directly from Google[1].

The patches for HDMI audio are on their way upstream. Current estimate is that they'll get merged by 4.12. If you're interested in tracking, there is a git tree[2] with patches under review on LKML.

Hope this helps.

[1] https://developers.google.com/android/images-preview#hikey
[2] https://git.linaro.org/people/john.stultz/android-dev.git/log/?h=dev/hikey-mainline-WIP

**Comment by vishalbhoj** [comment] 2017-01-05 08:25
Can you point me to the media files that you use for testing ?  Since we are just using s/w codecs, stuttering is expected on high resolution videos.

**Comment by dlinares-linux** [comment] 2017-05-09 09:16
Hi all.
I have just received an Hikey 620 with 2GB of RAM and I am also quite surprised of the video performance on that board for a reference platform.
I have followed the instructions from https://source.android.com/source/devices#620hikey to build from source as well as testing various pre-built images.
With all of them, when playing a 720p video from youtube/vimeo for example, some dropped frames appear after a few seconds, and on higher resolution videos, the video completely stops after seconds of playing.

Do I need to cool down the CPU?
Is there a quick way for me to check if the GPU is used correctly?
As for video decoding, I understand from the above that HW decoder is not used :-( so I am guessing for online video playing, I would need to consider another board, right?

**Comment by johnstultz-work** [comment] 2017-05-09 15:53
Yes, I'm afraid what you describe is expected behavior, as we don't have access to any hardware video decoding acceleration with HiKey 620. So video decoding is done on the cpu, which overburdens it, and eventually results in thermal throttling.  This has been a pain point, so we've worked with HiSi so that the new HiKey960 will eventually have accelerated hardware decoding enabled. However, that is not yet in place.

I haven't used the feature myself, but I believe the db410c board does have opensource accelerated video decoding, so that might be a better selection right now.

**Comment by docularxu** [comment] 2017-05-09 23:07
HW decoder is not available on HiKey.

**Comment by dlinares-linux** [comment] 2017-05-10 11:00
Thanks a lot both for your fast answers.
Just by curiosity, I have installed the AndroidTV image on Hikey (http://snapshots.linaro.org/android/android-tv-hikey-n/latest/) and now, I am a bit lost...
On this image, the video playback is pretty smooth (ExoPlayer, WebBrowser and Live Channel app), even on high resolution display and playing 720p without any freeze or dropped frames.
Am I right to still assume that software decoding is still used on these images?
Just wondering what the difference could be...

**Comment by johnstultz-work** [comment] 2017-05-10 20:45
Hmm. That is interesting. I think you're still correct that software decoding is being used.  I'd hazard a guess the videos are possibly of different bitrates, but I can't be sure from your description. I'll follow up with the AOSPTV folks about it though.  Thanks for pointing the difference out!

**Comment by johnstultz-work** [comment] 2017-05-11 03:45
So it seems that there are some extra libstagefright_soft_* packages added in the AOSPTV builds. 

These may provide some optimized software decoders that might explain the performance improvement.

I'll look into if adding these to the standard build also improves normal AOSP builds and include them if so.

Thanks again for pointing this out!

**Comment by johnstultz-work** [comment] 2017-05-15 22:40
dlinares-linux: I've submitted the following to AOSP:
https://android-review.googlesource.com/#/c/394733/

This seems to improve things slightly in my testing. But if you could confirm it resolves the difference for you, I'd appreciate it!

thanks
-john

**Comment by sdrobertw** [comment] 2017-08-22 14:39
@johnstultz-work @docularxu 

Can we close this issue?

**Comment by johnstultz-work** [comment] 2017-08-22 19:09
As far as I'm aware...

**Closed by johnstultz-work** 2017-08-22 19:09 UTC
Labels: help wanted, In progress
