### ISSUE TITLE
android-6.0.1_r16 build error "unknown type configfs"

### ISSUE THREAD

**Issue by ieei0214** [96boards/documentation#24] opened 2016-08-25 01:24 UTC
Hi,

https://github.com/96boards/documentation/wiki/CE-AOSP-RPB-HiKey-15.12-Build

I follow the steps to build android-6.0.1_r16 but get this error.

Does anyone know how to fix it?  Thanks.

Aidl Preprocess: out/target/common/obj/framework.aidl
host Executable: backtrace_test_32 (out/host/linux-x86/obj32/EXECUTABLES/backtrace_test_intermediates/backtrace_test32)
Install: out/host/linux-x86/lib/libbacktrace.so
host SharedLib: libbacktrace (out/host/linux-x86/obj/lib/libbacktrace.so)
Install: out/host/linux-x86/lib64/libbase.so
Host TableGen: libLLVMWrap (gen-intrinsic) <= frameworks/compile/libbcc/bcinfo/Wrap/../../../../../external/llvm/include/llvm/IR/Intrinsics.td
Host TableGen: libLLVMBitReader_2_7 (gen-intrinsic) <= frameworks/compile/libbcc/bcinfo/BitReader_2_7/../../../../../external/llvm/include/llvm/IR/Intrinsics.td
Host TableGen: libLLVMBitReader_3_0 (gen-intrinsic) <= frameworks/compile/libbcc/bcinfo/BitReader_3_0/../../../../../external/llvm/include/llvm/IR/Intrinsics.td
Host TableGen: libLLVMBitWriter_3_2 (gen-intrinsic) <= frameworks/compile/slang/BitWriter_3_2/../../../../external/llvm/include/llvm/IR/Intrinsics.td
Host TableGen: libbccCore (gen-intrinsic) <= frameworks/compile/libbcc/bcinfo/Wrap/../../../../../external/llvm/include/llvm/IR/Intrinsics.td
Install: out/host/linux-x86/bin/dalvikvm64
host SharedLib: libart (out/host/linux-x86/obj/lib/libart.so)
Install: out/host/linux-x86/lib64/libziparchive-host.so
Install: out/host/linux-x86/bin/fastboot
Copy: out/host/linux-x86/obj/EXECUTABLES/ld.mc_intermediates/Options.inc
Install: out/host/linux-x86/bin/make_ext4fs
Install: out/host/linux-x86/bin/simpleperf
Install: out/host/linux-x86/bin/tzdatacheck
Install: out/host/linux-x86/framework/hierarchyviewer.jar
Install: out/host/linux-x86/lib/libicui18n-host.so
host SharedLib: libjavacrypto_32 (out/host/linux-x86/obj32/lib/libjavacrypto.so)
host SharedLib: libsqlite_jni_32 (out/host/linux-x86/obj32/lib/libsqlite_jni.so)
Install: out/host/linux-x86/lib64/libicui18n-host.so
host SharedLib: libjavacore (out/host/linux-x86/obj/lib/libjavacore.so)
host SharedLib: libsqlite (out/host/linux-x86/obj/lib/libsqlite.so)
target SharedLib: libc_32 (out/target/product/hikey/obj_arm/SHARED_LIBRARIES/libc_intermediates/LINKED/libc.so)
Install: out/target/product/hikey/system/lib/libdl.so
target SharedLib: libc (out/target/product/hikey/obj/SHARED_LIBRARIES/libc_intermediates/LINKED/libc.so)
Install: out/target/product/hikey/system/lib64/libdl.so
out/host/linux-x86/bin/checkpolicy:  loading policy configuration from out/target/product/hikey/obj/ETC/sepolicy_intermediates/policy.conf
Writing local settings in /home/ieei/.jack
device/linaro/hikey/sepolicy/init.te:3:ERROR 'unknown type configfs' at token ';' on line 13742:
# init.hikey.usb.rc writes to /config/* to set up USB
allow init configfs:dir { create reparent rename rmdir setattr { { open getattr read search ioctl } { open search write add_name remove_name } } };
checkpolicy:  error(s) encountered while parsing configuration
make: *** [out/target/product/hikey/obj/ETC/sepolicy_intermediates/sepolicy] Error 1
make: *** Waiting for unfinished jobs....
Stopping background server
ERROR: No Jack server running
Killing background server
ERROR: No Jack server to kill
touch out/host/common/obj/JAVA_LIBRARIES/jack_intermediates/kill_server.stamp
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

**Comment by vchong** [comment] 2016-08-25 02:09
Duplicate of http://www.96boards.org/forums/topic/android-6-0-1_r16-build-error-unknown-type-configfs. Answered in the forum.

**Closed by vchong** 2016-08-25 02:09 UTC
