### ISSUE TITLE
Odd advice in ConsumerEdition/guides/open_embedded.md

### ISSUE THREAD

**Issue by daniel-thompson** [96boards/documentation#175] opened 2017-11-01 10:59 UTC
ConsumerEdition/guides/open_embedded.md  contains the following recommendation:

> Please Note: Certain version of Ubuntu / Debian may require the following lines be added to your
> /etc/apt/sources.list. Executing the following commands will append these lines to your source.list.
>
> $ echo "deb http://deb.debian.org/debian jessie main" | sudo tee -a /etc/apt/sources.list
> $ echo "deb-src http://deb.debian.org/debian jessie main" | sudo tee -a /etc/apt/sources.list

This is terrible advice. Adding the main repo on a debian jessie system is redundant; whilst adding it to an ubuntu or debian stretch system is crazy.

This text also deviates significantly from the upstream documentation this guide was copied from (I also have a question... is there a plan to keep this guide synchronized with the upstream doc.

From https://github.com/Linaro/documentation/blob/master/Reference-Platform/CECommon/OE.md :
> Please Note: If you are running Ubuntu 16.04 you will need to add the following line to your
> /etc/apt/sources.list
> 
> deb http://archive.ubuntu.com/ubuntu/ xenial universe

**Comment by Mani-Sadhasivam** [comment] 2017-11-01 11:38
@daniel-thompson I have to admit that I overlooked the package dependencies section. And I believe it has to be in sync with the Reference Platform guide. Let me change it. 

Also, in the RP guide there is a section about creating Mixed RFS image, which we removed in our guide after discussing with @fboudra. Should it be removed there also? 

Thanks for spotting!

**Comment by daniel-thompson** [comment] 2017-11-01 11:44
> Also, in the RP guide there is a section about creating Mixed RFS image, which we removed in our
> guide after discussing with @fboudra. Should it be removed there also?

No opinion on that one... I mostly spotted this issue because I noticed we were maintaining two nearly identical docs and what the process was to prevent them diverging. Perhaps you could just set a watch of some sort on the upstream page (as it happens a change of mine hit the upstream page yesterday).

**Comment by Mani-Sadhasivam** [comment] 2017-11-01 11:54
Sure. Will do. 

#176 addresses this issue.

Thanks once again!

**Comment by ndechesne** [comment] 2017-11-02 08:24
d'oh.. i am seeing that now.. can someone please fix the duplication issue? it is really wrong to duplicate documentation. Doing documentation is hard and painful, and duplicating it just makes everything worse. It is fine if someone wants to reorganize things (for the better), but when doing so, please talk to the people who contributed the doc first, and let's plan for the migration. 

doc is important, especially doc about OE, which is a difficult project to start with. so please suggest relevant pull request to resolve the duplication issues, and please do not *remove* existing section without a large consensus that it can be removed (e.g. the mixed rootfs build).

and good catch for the initial issue found by @daniel-thompson ;-)

**Comment by sdrobertw** [comment] 2018-03-31 23:08
@Mani-Sadhasivam has this issue been addressed? If not, please do so and close.

Thanks!

**Comment by Mani-Sadhasivam** [comment] 2018-04-01 02:08
@sdrobertw The issue is about having two identical OE guides (96Boards and Linaro). Should we remove 96Boards one and point it to Linaro page?

**Comment by Mani-Sadhasivam** [comment] 2018-06-04 07:11
@sdrobertw Waiting for your response!

Thanks

**Comment by sdrobertw** [comment] 2018-06-23 05:32
@Mani-Sadhasivam I would recommend to remove the Linaro/documentation one, and keep the 96boards/documentation one.

@ndechesne what do you think? Mani did a great job at transferring the content over and unifying it in the 96Boards doc rep.

**Comment by ndechesne** [comment] 2018-06-25 09:10
this documentation is not specific to 96boards.. so in theory it should be on the Linaro wiki.. however since most documentation efforts have been done in the 96boards wiki, it's probably better to keep this version..

**Comment by Mani-Sadhasivam** [comment] 2018-07-06 07:19
Closing as we agreed to keep the OE guide on both 96Boards and Linaro sites.

**Closed by Mani-Sadhasivam** 2018-07-06 07:19 UTC

**Comment by daniel-thompson** [comment] 2018-07-06 07:36
On Fri, 6 Jul 2018 at 08:19, Manivannan Sadhasivam <notifications@github.com>
wrote:

> Closing as we agreed to keep the OE guide on both 96Boards and Linaro
> sites.
>
Which one should we advise forum members to follow if they are having
problems?

**Comment by Mani-Sadhasivam** [comment] 2018-07-06 07:37
@daniel-thompson Should be 96Boards one!
